name: music_feature_analyzer_example
description: A comprehensive example demonstrating all features of the music_feature_analyzer package
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Music Feature Analyzer Package
  music_feature_analyzer:
    path: ../
  
  # UI Dependencies
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  logger: ^2.4.0
  
  # File Picker
  file_picker: ^10.3.3
  
  # Additional UI Dependencies
  lottie: ^3.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/images/